name: Test Project

on:
 pull_request:
   brancjes:
      - main

jobs:
  test:
    runs-on: ubunto-latest
    container:
      image: node:20
    steps:
      - uses: action/chechout@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - run: npm run build
   